config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :classrooms

  resources :courses

  resources :students

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  validates_presence_of  :students_id, :courses_id

  before_save :get_time
  def get_time
    self.entry_at ||= Time.current

  end
end

app/models/course.rb
class Course < ActiveRecord::Base
    validates_presence_of  :name, :description, :status
end

app/models/student.rb
class Student < ActiveRecord::Base
      validates_presence_of  :name, :register_number, :status
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  # GET /classrooms
  # GET /classrooms.json
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/1
  # GET /classrooms/1.json
  def show
          @student = Classroom.find(params[:id])
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new classroom_params
    respond_to do |format|
      if @classroom.save
        format.html { redirect_to @classroom, notice: 'Classroom was successfully created.' }
        format.html { render action: 'show', status: :created, location: @classroom }
      else
        format.html { render action: 'new' }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1
  # PATCH/PUT /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to @classroom, notice: 'Classroom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to classrooms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classroom_params
      params.require(:classroom).permit(:students_id, :courses_id)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
      @course = Course.find(params[:id])
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new course_params

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :status)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
      @student = Student.find(params[:id])
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new student_params
    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private
  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :register_number, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/classrooms/_form.html.erb
<form accept-charset="UTF-8" action="/classrooms" class="nifty_form" id="new_classroom" method="post">
    <div style="display:none">
        <input name="utf8" type="hidden" value="✓">
        <input name="authenticity_token" type="hidden" value="rN+eovP8RZN2qGM7HPQwJcu1X2O5LnCJL9GnbMmBL18=">
    </div>
    <hr class="colorgraph">
    <div class="col-xs-6 col-sm-6 col-md-6">
        <div class="form-group">
            <input id="classroom_students_id" name="classroom[students_id]" type="text" class="form-control input-lg" placeholder="Id Estudante" tabindex="1">
        </div>
        <div class="form-group">
            <input id="classroom_courses_id" name="classroom[courses_id]" type="text" class="form-control input-lg" placeholder="Id Curso" tabindex="3">
        </div>
        <input class="btn btn-default" name="commit" type="submit" value="Cadastrar">
    </div>
</form>

app/views/classrooms/edit.html.erb
<h1>Editing classroom</h1>

<%= render 'form' %>

<%= link_to 'Show', @classroom %> |
<%= link_to 'Back', classrooms_path %>

app/views/classrooms/index.html.erb
<h1>Listing classrooms</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td><%= link_to 'Show', classroom %></td>
        <td><%= link_to 'Edit', edit_classroom_path(classroom) %></td>
        <td><%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Classroom', new_classroom_path %>

app/views/classrooms/new.html.erb
<div class="panel panel-success">
    <div class="panel-heading">
        <h1 ng-if="name" align="middle">Nova Matricula</h1>
    </div>
    <div class="panel-body">
<%= render 'form' %>
</div>
</div>

app/views/classrooms/show.html.erb
<div class="panel panel-success">
    <div class="panel-heading">
        <h1 ng-if="name" align="middle" id="notice"><%= notice %></h1>
    </div>
    <div class="panel-body">
Student ID: <%= @classroom.students_id %> <br>
Course ID: <%= @classroom.courses_id %> <br>
entry: <%= @classroom.entry_at %> <br>
</div>
</div>

app/views/courses/_form.html.erb
<form accept-charset="UTF-8" action="/courses" class="nifty_form" id="new_course" method="post">
    <div style="display:none">
        <input name="utf8" type="hidden" value="✓">
        <input name="authenticity_token" type="hidden" value="rN+eovP8RZN2qGM7HPQwJcu1X2O5LnCJL9GnbMmBL18=">
    </div>
    <hr class="colorgraph">
    <div class="col-xs-6 col-sm-6 col-md-6">
        <div class="form-group">
            <input id="course_name" name="course[name]" type="text" class="form-control input-lg" placeholder="Nome" tabindex="1">
        </div>
        <div class="form-group">
            <input id="course_description" name="course[description]" type="text" class="form-control input-lg" placeholder="Descrição" tabindex="3">
        </div>
         <div class="form-group">
            <input id="course_status" name="course[status]" type="text" class="form-control input-lg" placeholder="Status" tabindex="3">
        </div>

        <input class="btn btn-default" name="commit" type="submit" value="Cadastrar">
    </div>
</form>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<div class="panel panel-success">
    <div class="panel-heading">
        <h1 ng-if="name" align="middle">Novo Curso</h1>
    </div>
    <div class="panel-body">
<%= render 'form' %>
</div>
</div>

app/views/courses/show.html.erb
<div class="panel panel-success">
    <div class="panel-heading">
        <h1 ng-if="name" align="middle" id="notice"><%= notice %></h1>
    </div>
    <div class="panel-body">
Name: <%= @course.name %> <br>
Description: <%= @course.description %> <br>
Status: <%= @course.status %> <br>
</div>
</div>

app/views/home/index.html.erb
<div class="container-fluid" ng-app="ProfiencyTest" ng-controller="HomeController">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h1 ng-if="name" align="middle">Profiency Test</h1>
    </div>
    <div class="panel-body">
      <a class="btn btn-default" type="submit" href="students/new">Cadastrar Estudante</a>
      <a class="btn btn-default" type="submit" href="courses/new">Cadastrar Curso</a>
      <a class="btn btn-default" type="submit" href="classrooms/new">Matricular Estudante</a>
      </form>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProficiencyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/javascript" src="assets/Validate.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<form accept-charset="UTF-8" action="/students" class="nifty_form" id="new_student" method="post" name="myForm">
    <div style="display:none">
        <input name="utf8" type="hidden" value="✓">
        <input name="authenticity_token" type="hidden" value="rN+eovP8RZN2qGM7HPQwJcu1X2O5LnCJL9GnbMmBL18=">
    </div>
    <hr class="colorgraph">
    <div class="col-xs-6 col-sm-6 col-md-6">
        <div class="form-group">
            <input id="student_name" onBlur="validate(myForm.student_name)" name="student[name]" type="text" class="form-control input-lg" placeholder="Nome" tabindex="1">
        </div>
        <div class="form-group">
            <input id="student_register" name="student[register_number]" type="text" class="form-control input-lg" placeholder="Numero de Registro" tabindex="3">
        </div>
         <div class="form-group">
            <input id="student_status" name="student[status]" type="text" class="form-control input-lg" placeholder="Status" tabindex="3">
        </div>

        <input class="btn btn-default" name="commit" type="submit" value="Cadastrar">
    </div>
</form>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<div class="panel panel-success">
    <div class="panel-heading">
        <h1 ng-if="name" align="middle">Novo Estudante</h1>
    </div>
    <div class="panel-body">
<%= render 'form' %>
</div>
</div>

app/views/students/show.html.erb
<div class="panel panel-success">
    <div class="panel-heading">
        <h1 ng-if="name" align="middle" id="notice"><%= notice %></h1>
    </div>
    <div class="panel-body">
Name: <%= @student.name %> <br>
Register Number: <%= @student.register_number %> <br>
Status: <%= @student.status %> <br>
</div>
</div>